services:
  - type: web
    name: advanced-typingspot
    env: node
    buildCommand: npm install && NEXT_DISABLE_ESLINT=1 NEXT_DISABLE_TYPE_CHECKS=1 npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free 